global using Models;
global using Repository.IRepositoryGeneric;
global using Microsoft.AspNetCore.Identity;
global using AutoMapper;
global using System.ComponentModel.DataAnnotations;
global using Microsoft.IdentityModel.Tokens;
global using System.IdentityModel.Tokens.Jwt;
global using System.Security.Claims;
global using System.Text;